### ISSUE TITLE
2016/02/25 Thu

### ISSUE THREAD

**Issue by peccu** [peccu/outer-storage#1]
- cash / https://github.com/dthree/cash/

JSで書いたシェル．Windowsでも動く．
各コマンドを単体でインストールすることもできる．
- Safariのヒストリをここに流し込む．

確かsqliteで抜き出せる．一覧から取捨選択してタイトルとURLをmdフォーマットで貼り付ける．
- 本のどこを読んだか記録する
- Common Lispでheroicにデプロイ．実践Common Lispのを動かしてみる．
- ui-bootstrap (https://angular-ui.github.io/bootstrap/) のモーダルはhtmlとbodyのスタイルによって、勝手にページ先頭までスクロールされてしまう．

スクロールせず表示される例: http://run.plnkr.co/plunks/fFSfwa/
スクロールして表示される例: http://run.plnkr.co/plunks/08JANs/

再現する条件．下記のどれかを削るとスクロールしない。

``` css
html {
  overflow-y: scroll;
  height: 100%;
}
body {
  height: 100%;
}
```
- Safariから閲覧中のページをここに移す仕組みが必要
- 今日も1つzshの設定を移行．

そろそろ移行できる設定がなくなってくる．.emacs.dの切り出しも進める．
- gh-pagesに書き出して，タグで検索できるようにする
- Common LispでAPI
- 家族のグループでissue管理
- protractor便利
